load("@aspect_rules_js//js:defs.bzl", "js_library")

js_library(
    name = "tag_map",
    srcs = ["tag-map.json"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "pricing",
    srcs = ["pricing.json"],
    visibility = ["//visibility:public"],
)

js_library(
    name = "triggers",
    srcs = ["triggers.json"],
    visibility = ["//visibility:public"],
)
